### ISSUE TITLE
I'm getting an error when I try to compile.

### ISSUE THREAD

**Issue by russc** [AljoschaMeyer/atom-lilycompile#1]
Lilypond Compilation Error
/bin/sh: lilypond: command not found

**Comment by AljoschaMeyer** [comment]
That's great - the last version of this would have failed silently.

The package works by [executing](http://lilypond.org/doc/v2.18/Documentation/usage/command_002dline-usage) the command `lilypond` in your shell. The error message says that this command is not on the path. For this to work, you need to have lilypond already installed on your computer. Then, you have two possible solutions to get this to work:

1. Add the lilypond executable to your [path](https://en.wikipedia.org/wiki/PATH_%28variable%29)
2. Set the `Binary` value in the lilycompile settings to the full path of the lilypond executable.

If this wasn't clear enough (or too technical), I can explain this in more detail - knowing your operating system would help as well.

**Comment by russc** [comment]
I'm on MacOS.

**Comment by AljoschaMeyer** [comment]
Have you ever run lilypond by hand, or only through GUIs? When you installed lilypond, it should have put an executable file named `lilypond` somewhere on your computer. Just paste the full path of this file into the `Binary` setting for the lilycompile package (inside atom).

**Comment by russc** [comment]
I've never used the GUI's.  I specifically want to use atom.  I understand your instructions and I've made some progress; however, since I'm on a mac there is only the app file to point to and I get this error /bin/sh: /Applications/lilypond: No such file or directory
Close All

**Comment by AljoschaMeyer** [comment]
I'm not a MacOS user, so I can't really help you here. Basically you need to find out which file is the lilypond executable. Maybe [this](http://lilypond.org/macos-x.html) can help?

The link seems to suggest that `/Applications//LilyPond.app/Contents/Resources/bin/lilypond` might be what you need. You can try putting that as the `Binary` setting.

**Comment by russc** [comment]
On the contrary, you were very helpful in pointing me in a direction.  I was able to find this http://lilypond.1069038.n5.nabble.com/Lilypond-in-Mac-OS-X-Terminal-td137561.html to solve the binary setting file.  Also, I much appreciate this project.  I can't wait to start using the benefits of atom with my music writing needs.

**Comment by russc** [comment]
Bingo!  It's working beautifully. 
![screen shot 2016-07-20 at 10 43 05 am](https://cloud.githubusercontent.com/assets/738104/16992898/c6b371f4-4e66-11e6-8715-094dac444c99.png)

**Comment by okhick** [comment]
@russc Can you share what you did to implement this into Atom? I'm able to compile from Terminal but I can't seem to add it into lilycomplie.
