### ISSUE TITLE
SVG request

### ISSUE THREAD

**Issue by pleskoFER** [AljoschaMeyer/atom-lilycompile#3]
Hi, this atom plugin is nicely done. Great job! 

It would be great if you could make svg support also. I use this feature with every score I write. Using Inkscape and importing svg I can get better quality PDFs and easily change things that I overlooked in editor/ide.

Thank you for your good will!

**Comment by AljoschaMeyer** [comment]
Just to force myself to implement this: I'll tackle this in a few hours. Should be pretty easy to do.

**Comment by AljoschaMeyer** [comment]
Published version 0.5.0 which adds an `svg` output type.

There's one problem though: When the rendered music does not fit on one page, lilypond creates multiple svg files (the same is true for png as well). So as long as `foo.ly` fits one one page, the output file is `foo.svg` (or `foo.png` respectively). But once `foo.ly` is long enough, this becomes `foo-page-1.svg` and `foo-page-2.svg` (and annoyingly enough the naming convention differs for pngs: `foo-page1.png` and `foo-page2.png`.

I did not want to spend too much time on this (I don't use this package a lot anymore, and the codebase is quite messy), so I did not implement anything to handle this. Short scores are previewed correctly, longer ones don't work. Some problems whith correctly handling this situation:

- Detecting whether lilypond produced only one file, or multiple files. I did not find an easy way to get this information from lilypong, so this would involve checking the output manually (which requires some restructuring of the code).
- Opening multiple files in atom would not be very convenient, so they'd probably ned to be concatenated.

Neither of these are impossible, but I don't really want to spend the necessary time on this. Also, this package is only intended for quick previews in the editor, not for actually rendering the final result, or editing it. But with this update, you can select svg as the output format and use the option to not open the output in atom at all. Then you can use inkscape to view (and edit) the previews.
