### ISSUE TITLE
"Build after save" option?

### ISSUE THREAD

**Issue by samestep** [AljoschaMeyer/atom-lilycompile#6]
Would it be possible to add a "Build LilyPond after saving" option similar to [the option found in Atom-LaTeX][atom-latex]? If not, how could I add such a feature to my personal Atom config?

[atom-latex]: https://github.com/James-Yu/Atom-LaTeX/blob/v0.8.4/lib/config.coffee#L51-L56

**Comment by samestep** [comment]
I just realized that `lilycompile:compile` automatically saves the file; still, it would be nice to have the option to be able to use the standard save command and have that trigger `lilycompile:compile` rather than the other way around.

**Comment by AljoschaMeyer** [comment]
Since this package is rather unmaintained, I'm not really motivated to figure out how to implement this.

Is it possible to set keybindings per file type? In that case, you could simply map `ctrl + s` to the compile command rather than save.

**Comment by AljoschaMeyer** [comment]
Thanks for the pull request. Published as [0.7.0](https://github.com/AljoschaMeyer/atom-lilycompile/releases/tag/v0.7.0).
